brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
enum_discrim_align_threshold = 10
fn_params_layout = "Compressed"
fn_single_line = true
hard_tabs = false
imports_layout = "Horizontal"
max_width = 200
struct_lit_width = 100
trailing_comma = "Never"
chain_width = 50
struct_lit_single_line = false